# docker-compose.yml

version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src/web:/app/src/web
    command: bash -c "cd src/web && flask run --host=0.0.0.0"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/app/src/api
    command: bash -c "cd src/api && python -m uvicorn main:app --host 0.0.0.0 --port 8000"
